name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Building the Docker image
      run: docker build -t start-wars-codetest .
    - name: Checking code linting
      run: npm run lint
    - name: Running jest tests
      run: npm run test
